name: Deployment workflow
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: update code in server
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /root/tendencias-actions
            git reset --hard
            git pull origin master
          host: ${{ secrets.HOST }}
          user: root
          port: 22
          Key: "${{secrets.SSH_KEY}}"
          args: "-tt"

      - name: build code in server
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /root/tendencias-actions
            go clean
            go build 
            ls -l
          host: ${{ secrets.HOST }}
          user: root
          port: 22
          Key: "${{secrets.SSH_KEY}}"
          args: "-tt"

      - name: restart app
        uses: fifsky/ssh-action@master
        with:
          command: |
            systemctl restart webserver
            systemctl status webserver
          host: ${{ secrets.HOST }}
          user: root
          port: 22
          Key: "${{secrets.SSH_KEY}}"
          args: "-tt"
