name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: root
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /root/tendencias-actions
            git reset --hard
            git pull origin master
            go clean
            go build
            ls -l
            systemctl restart webserver
            systemctl status webserver